/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#2a14b4',
        'primary-container': '#4338ca',
        'on-primary': '#ffffff',
        'on-primary-container': '#c1beff',
        'primary-fixed': '#e3dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#100069',
        'on-primary-fixed-variant': '#372abf',
        'inverse-primary': '#c3c0ff',

        'secondary': '#006398',
        'secondary-container': '#5bb8fe',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00476e',
        'secondary-fixed': '#cce5ff',
        'secondary-fixed-dim': '#93ccff',
        'on-secondary-fixed': '#001d31',
        'on-secondary-fixed-variant': '#004b73',

        'tertiary': '#00451a',
        'tertiary-container': '#005f26',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#60dd7c',
        'tertiary-fixed': '#7ffc97',
        'tertiary-fixed-dim': '#62df7d',
        'on-tertiary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#005320',

        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        'background': '#faf8ff',
        'on-background': '#131b2e',
        'surface': '#faf8ff',
        'on-surface': '#131b2e',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-variant': '#dae2fd',
        'on-surface-variant': '#464554',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-tint': '#5148d7',

        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'outline': '#777586',
        'outline-variant': '#c7c4d7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '2.5rem',
        'space-4xl': '3rem',
        'margin-mobile': '1rem',
        'margin-tablet': '1.5rem',
        'margin-desktop': '2rem',
        'layout-margin-desktop': '2rem',
        'gutter-mobile': '1rem',
        'gutter-tablet': '1.25rem',
        'gutter-desktop': '1.5rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'sans-serif'],
        'telemetry-num': ['Plus Jakarta Sans', 'monospace'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'label-xs-mono': ['Plus Jakarta Sans', 'monospace'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'title-md': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'display-lg-mobile': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'telemetry-num': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-md': ['16px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
